### ISSUE TITLE
database

### ISSUE THREAD

**Issue by monchichis** [fannyhasbi/apotek-ci#8]
databasenya di sebelah mana gan ?
udah pake fungsi search apotek.sql di folder nya gak ketemu

**Comment by 280397** [comment]
jahat

**Comment by fannyhasbi** [comment]
I am sorry, but this is an old project and I didn't maintained it for years. I haven't the db anymore.

I think the DB seems like this, please kindly check if it still work
https://github.com/fannyhasbi/apotek/blob/master/apotek.sql

From now, this project is archived. Thanks! :smile:
